project: mes
applications:
  - web-socket-service
build:
  container:
    enabled: true
  node:
    enabled: false
    image: library/node:18
    framework: npm
test:
  enabled: false
  image: cypress/base:20.17.0
  framework: cypress
deploy:
  gitops:
    enabled: true