version: '3.8'

services:
  web-socket-service:
    container_name: web-socket-service
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - 8081:8081
    networks:
      - thingable
    restart: always
    env_file:
      - .docker.env

networks:
  thingable:
    external: true
    name: thingable